/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Application */

#ifndef _Included_Application
#define _Included_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Application
 * Method:    calcunatePonaparte
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Application_calcunatePonaparte
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
